### ISSUE TITLE
VIDEO 5 Creating custom stateful

### ISSUE THREAD

**Issue by ddiawara** [romanejaquez/orilla_fresca_app#13]
Hi when i move mainAppBar detailspage , i have this error 

<img width="724" alt="image" src="https://user-images.githubusercontent.com/62718811/138192753-99afdf50-e71c-408f-93f7-d6f01c783b18.png">

```sh
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderCustomMultiChildLayoutBox object was given an infinite size during layout.

This probably means that it is a render object that tries to be as big as possible, but it was put inside another render object that allows its children to pick their own size.
The nearest ancestor providing an unbounded height constraint is: RenderFlex#8fee5 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=896.0)
...  size: Size(414.0, 896.0)
...  direction: vertical
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: center
...  verticalDirection: down
The constraints that applied to the RenderCustomMultiChildLayoutBox were: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=Infinity)
The exact size it was given was: Size(414.0, Infinity)

See https://flutter.dev/docs/development/ui/layout/box-constraints for more information.

The relevant error-causing widget was: 
  Scaffold Scaffold:file:///Users/daman/MISSION/PERSO/Projects/orilla_fresca/lib/widgets/mainappbar.dart:26:12
When the exception was thrown, this was the stack: 
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:2205:9)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2299:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1991:7)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1993:6)
#4      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:5)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#9      _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1388:11)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#11     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#12     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#13     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#16     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1388:11)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#18     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#19     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#20     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#22     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:437:14)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#24     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#25     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1097:7)
#26     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#27     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#32     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1388:11)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#40     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#41     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
#42     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#51     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#57     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3422:13)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#61     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:745:15)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1858:7)
#77     RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
#78     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1713:7)
#79     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:885:18)
#80     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
#81     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#82     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#83     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#84     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#85     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderCustomMultiChildLayoutBox#81825 relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=Infinity)
...  size: Size(414.0, Infinity)
RenderObject: RenderCustomMultiChildLayoutBox#81825 relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=Infinity)
  size: Size(414.0, Infinity)
...  child 1: RenderConstrainedBox#e9827 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.appBar
...    constraints: MISSING
...    size: MISSING
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=100.0)
...    child: RenderSemanticsAnnotations#82e42 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none>
...      constraints: MISSING
...      semantic boundary
...      size: MISSING
...      child: RenderAnnotatedRegion<SystemUiOverlayStyle>#74d3d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        child: RenderPhysicalModel#10235 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...          elevation: 0.0
...          color: Color(0x00000000)
...          shadowColor: Color(0x00000000)
...          shape: BoxShape.rectangle
...          borderRadius: BorderRadius.zero
...  child 2: RenderStack#53334 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.floatingActionButton
...    constraints: MISSING
...    size: MISSING
...    alignment: Alignment.centerRight
...    textDirection: ltr
...    fit: loose
...    child 1: RenderTransform#3f94c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: not positioned; offset=Offset(0.0, 0.0)
...      constraints: MISSING
...      size: MISSING
...      transform matrix: [0] 0.0,0.0,0.0,0.0
[1] 0.0,0.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...      origin: null
...      alignment: Alignment.center
...      textDirection: ltr
...      transformHitTests: true
...      child: RenderTransform#830c4 NEEDS-LAYOUT NEEDS-PAINT
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        transform matrix: [0] 0.7,0.7,0.0,0.0
[1] -0.7,0.7,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        origin: null
...        alignment: Alignment.center
...        textDirection: ltr
...        transformHitTests: true
...  child 3: RenderPointerListener#81536 NEEDS-LAYOUT NEEDS-PAINT
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.statusBar
...    constraints: MISSING
...    size: MISSING
...    behavior: opaque
...    listeners: down
====================================================================================================

======== Exception caught by rendering library =====================================================
_RenderInkFeatures object was given an infinite size during layout.
The relevant error-causing widget was: 
  Scaffold Scaffold:file:///Users/daman/MISSION/PERSO/Projects/orilla_fresca/lib/widgets/mainappbar.dart:26:12
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderPhysicalModel object was given an infinite size during layout.
The relevant error-causing widget was: 
  Scaffold Scaffold:file:///Users/daman/MISSION/PERSO/Projects/orilla_fresca/lib/widgets/mainappbar.dart:26:12
====================================================================================================





RenderBox was not laid out: RenderClipRRect#f5e5a relayoutBoundary=up3
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1929 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ClipRRect ClipRRect:file:///Users/daman/MISSION/PERSO/Projects/orilla_fresca/lib/pages/detailspage.dart:34:13
```

**Comment by ddiawara** [comment]
My bad i was put mainappbar in scaffold
